### ISSUE TITLE
Unknown field pavg1

### ISSUE THREAD

**Issue by Serverfrog** [Rebmiami/FanMod#3]
This is my first usage of Mods inside Powder toy.

Im running TPT Version v96.2.350 on Windows.
When i spawn GRPH, BGPH or FFLD i get `Unknown filed (pavg0)`/`(pavg1)` and the corresponding line of implementation.,

On FFLD it is line 907(pavg1) and 981(pavg1)
GRPH it is line 1274
BGPH it is line 1459

**Comment by Rebmiami** [comment]
This is a result of newer TPT snapshots changing the fields `pavg0` and `pavg1` to `tmp3` and `tmp4` respectively and the Lua API lacks backward compatibility for the old property names. This should be fixed in later TPT snapshots but I will fix this so that it works in the current snapshot. Thank you.
